
USE `bdbasehotel1`;
-- Nuevas tablas 
-- lo nuevo de manolo
-- tabla Organizacion --
DROP TABLE IF EXISTS `Tborganizacion`;
CREATE TABLE `Tborganizacion` (
  `idOrg`         int not NULL primary key auto_increment,
  `nitDni`        varchar(15) DEFAULT '',
  `nroPisos`      int DEFAULT 0,
  `desGeneral1`   varchar(250) DEFAULT '',
  `desGeneral2`   varchar(250) DEFAULT '',  
  `IdCiudad`      int DEFAULT 0,
  `nombOrg`       varchar(60) DEFAULT '',
  `dirbOrg`       varchar(50) DEFAULT '',
  `noTelf1`       varchar(15) DEFAULT '',
  `noTelf2`       varchar(15) DEFAULT '',
  `emailOrg`      varchar(100) DEFAULT '',
  `nroHabXpiso`   int DEFAULT 0,
  `aforoPersonas` int DEFAULT 0,
  `rutaImagen`    varchar(100) DEFAULT '',
  `status`        tinyint  not null DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Se llenan las tablas

-- datos tabla organizacion -- 
insert into `Tborganizacion` values(1   ,  '11111'   ,   2  ,'Situada en la vía Tocaima – Viotá y está especialmente diseñada para descansar y descomunicarse del mundo exterior, gozando de una piscina cómoda, mangos y limones propios de la finca. La cabaña cuenta con las siguientes características:'   ,   'Si quieres dedicarte a contemplar la naturaleza, tienes las aguas cristalinas que han descendido desde lo alto de los picos nevados,'   ,  39  ,  ' Hotel numero-1'  ,  'direccion del hotel-1'  ,  '315-315-3010'  ,  '320-315-2015'  ,  'correohotelnumero161@correo.com'  ,  3  ,  106  ,  'dir1/imgHotel/'  ,  1);
insert into `Tborganizacion` values(2   ,  '11112'   ,   1  ,'Habitacion con vista al mar amobladas'   ,   'El arco iris se derritió y está en La Macarena, viaja en un río de 5 colores: amarillo, azul, rojo, verde y rosado, principalmente.'   ,  39  ,  ' Hotel numero-2'  ,  'direccion del hotel-2'  ,  '315-315-3031'  ,  '320-315-2231'  ,  'correohotelnumero147@correo.com'  ,  1  ,  92  ,  'dir2/imgHotel/'  ,  1);
insert into `Tborganizacion` values(3   ,  '11113'   ,   1  ,'Hermosos paisajes de Antioquia'   ,   'En los departamentos de Huila y Tolima, (entre los que se encuentra este desierto), se celebran las fiestas de San Pedro y San Juan, y el Festival Folclórico y Reinado para Nacional del Bambuco'   ,  39  ,  ' Hotel numero-3'  ,  'direccion del hotel-3'  ,  '315-315-3052'  ,  '320-315-2447'  ,  'correohotelnumero168@correo.com'  ,  4  ,  70  ,  'dir3/imgHotel/'  ,  1);
insert into `Tborganizacion` values(4   ,  '11114'   ,   2  ,'El Bleu Hills Glamping Llanogrande está situado en Rionegro, en la región de Antioquia, y ofrece alojamiento con aparcamiento privado gratuito y acceso a una bañera de hidromasaje.'   ,   'A los pies del Pilón de Azúcar, un monte que funciona como atractivo turístico, se extiende la Playa de Oro, cuyo color le da el nombre y que se presta para descansar en la misma con una sombra natural hasta eso de las 2:00 p.m'   ,  39  ,  ' Hotel numero-4'  ,  'direccion del hotel-4'  ,  '315-315-3073'  ,  '320-315-2663'  ,  'correohotelnumero124@correo.com'  ,  5  ,  120  ,  'dir4/imgHotel/'  ,  1);
insert into `Tborganizacion` values(5   ,  '11115'   ,   1  ,'El Chalet Ecoturismo La Nohelia, situado en Jericó, rodeado por los cultivos de café famosos de la zona, ofrece restaurante y préstamo de bicicletas.'   ,   ' por el avistamiento de las ballenas yubartas que, huyendo de las aguas frías de la Antártida, llegan hasta estas costas para aparearse en la región que se ha denominado la salacuna de estos mamíferos y para los colombianos.'   ,  39  ,  ' Hotel numero-5'  ,  'direccion del hotel-5'  ,  '315-315-3094'  ,  '320-315-2879'  ,  'correohotelnumero191@correo.com'  ,  4  ,  84  ,  'dir5/imgHotel/'  ,  1);
insert into `Tborganizacion` values(6   ,  '11116'   ,   1  ,'El Santa Fé Hostel se encuentra a 3,8 km del parque acuático Kanaloa. El camping proporciona WiFi gratuita. El aeropuerto Olaya Herrera, el más cercano, está a 62 km del camping.'   ,   'las caminatas o cabalgatas que se ofrecen este santuario natural ubicado dentro del Parque Nacional de los Nevados o de sus hermosos jardines'   ,  39  ,  ' Hotel numero-6'  ,  'direccion del hotel-6'  ,  '315-315-3115'  ,  '320-315-3095'  ,  'correohotelnumero125@correo.com'  ,  2  ,  81  ,  'dir6/imgHotel/'  ,  1);
insert into `Tborganizacion` values(7   ,  '11117'   ,   2  ,'El Aguayacanes se encuentra en San Rafael y ofrece un jardín. Guatapé se encuentra a 15 km del camping, mientras que Barbosa está a 38 km.'   ,   'Este volcán se eleva hasta los 5.400 mt. de altura y si subes, te encontrarás con la nieve hacia los 4.800 mt.; desde 1.985 la capa de nieve ha venido reduciéndose'   ,  39  ,  ' Hotel numero-7'  ,  'direccion del hotel-7'  ,  '315-315-3136'  ,  '320-315-3311'  ,  'correohotelnumero100@correo.com'  ,  5  ,  112  ,  'dir7/imgHotel/'  ,  1);
insert into `Tborganizacion` values(8   ,  '11118'   ,   1  ,'Colombia cuenta con un sistema de Parques Nacionales Naturales que permite al visitante apreciar la majestuosidad de nuestra geografía, así como la riqueza de nuestra fauna y flora. Conoce algunas curiosidades de Colombia '   ,   'La Laguna de la Plaza, el Púlpito del diablo o el Pan de azúcar, permanecen en la memoria de los más aventureros. Aquí puedes practicar senderismo, montañismo y escalada'   ,  39  ,  ' Hotel numero-8'  ,  'direccion del hotel-8'  ,  '315-315-3157'  ,  '320-315-3527'  ,  'correohotelnumero188@correo.com'  ,  5  ,  98  ,  'dir8/imgHotel/'  ,  1);
insert into `Tborganizacion` values(9   ,  '11119'   ,   1  ,' El primer Parque Nacional Natural de Colombia fue La Cueva de los Guácharos, declarado el 9 de noviembre de 1960. Por esa razón, en esta fecha se celebra el Día de los Parques Naturales en nuestro país. '   ,   'Reserva Natural Victoria Regia, que lleva el nombre del nenúfar o lirio de agua más grande entre todos y que solo se da en La Amazonía'   ,  39  ,  ' Hotel numero-9'  ,  'direccion del hotel-9'  ,  '315-315-3178'  ,  '320-315-3743'  ,  'correohotelnumero173@correo.com'  ,  5  ,  76  ,  'dir9/imgHotel/'  ,  1);
insert into `Tborganizacion` values(10  ,  '11120'   ,   3  ,'El Parque Nacional Natural Uramba Bahía Málaga.  se ubica en las costas del pacífico colombiano y es reconocido internacionalmente por ser un privilegiado escenario para apreciar la migración de ballenas jorobadas'   ,   'El Monumento a la Santandereanidad, el torrentismo, visitar el mercado campesino o entrar al Acuaparque Nacional del Chicamocha, pueden ser algunos de los planes a realizar en este increíble parque'   ,  39  ,  ' Hotel numero-10'  ,  'direccion del hotel-10'  ,  '315-315-3199'  ,  '320-315-3959'  ,  'correohotelnumero142@correo.com'  ,  4  ,  131  ,  'dir10/imgHotel/'  ,  1);
insert into `Tborganizacion` values(11  ,  '11121'   ,   3  ,'El Parque Las Orquídeas se presenta como uno de los lugares ideales para observar nuestra diversidad de flora y fauna.'   ,   'Se encuentra en medio del océano Atlántico, conocida por su clima, en la que podemos encontrar maravillosos paisajes, playas de piedras, acantilados increíbles , bosques frondosos y algunos de los mejores parques botánicos del mundo'   ,  39  ,  ' Hotel numero-11'  ,  'direccion del hotel-11'  ,  '315-315-3220'  ,  '320-315-4175'  ,  'correohotelnumero160@correo.com'  ,  5  ,  219  ,  'dir11/imgHotel/'  ,  1);
insert into `Tborganizacion` values(12  ,  '11122'   ,   2  ,'Las 15.000 hectáreas del Parque Natural Nacional Tayrona ofrecen al visitante una paradisíaca combinación de naturaleza, historia precolombina, aventura y relajación.'   ,   'Se puede llegar a este lugar para explorar las minas de sal que están abiertas al público, donde se pueden apreciar los increíbles espejos de agua adecuados con hermosa iluminación'   ,  39  ,  ' Hotel numero-12'  ,  'direccion del hotel-12'  ,  '315-315-3241'  ,  '320-315-4391'  ,  'correohotelnumero140@correo.com'  ,  4  ,  113  ,  'dir12/imgHotel/'  ,  1);
insert into `Tborganizacion` values(13  ,  '11123'   ,   1  ,'La Playa La Aguada, ubicada en el Parque Natural Utría, es la primera playa de Colombia con certificación en turismo sostenible.'   ,   'El Tuparro es una reserva natural que ofrece al visitante hermosos ríos, gran variedad de vegetación, la posibilidad de ver jaguares, tapires y animales de la región, además de cientos de especies de aves'   ,  39  ,  ' Hotel numero-13'  ,  'direccion del hotel-13'  ,  '315-315-3262'  ,  '320-315-4607'  ,  'correohotelnumero122@correo.com'  ,  2  ,  89  ,  'dir13/imgHotel/'  ,  1);
insert into `Tborganizacion` values(14  ,  '11124'   ,   2  ,'Colombia es uno de los países con más biodiversidad en el mundo, los colores, la fauna y la flora que lo caracterizan son motivo de orgullo.'   ,   'Ofrece paisajes espectaculares pasando por desiertos, playas, bahías con flamencos rosados y gigantes dunas de arena dorada. '   ,  39  ,  ' Hotel numero-14'  ,  'direccion del hotel-14'  ,  '315-315-3283'  ,  '320-315-4823'  ,  'correohotelnumero186@correo.com'  ,  3  ,  106  ,  'dir14/imgHotel/'  ,  1);
insert into `Tborganizacion` values(15  ,  '11125'   ,   3  ,'Parque Nacional Natural Amacayacu,  en el Amazonas, con más de 40 años de historia representa el 40% del Trapecio Amazónico y debido a su ecosistema de selva húmeda tropical cálida y bosques inundables'   ,   ' Caño Cristales, llamado por muchos como el “río más hermoso del mundo”. Esto es debido a los diversos colores que se pueden observar en el fondo gracias a la presencia de plantas acuáticas que le dan esas tonalidades características'   ,  39  ,  ' Hotel numero-15'  ,  'direccion del hotel-15'  ,  '315-315-3304'  ,  '320-315-5039'  ,  'correohotelnumero119@correo.com'  ,  3  ,  192  ,  'dir15/imgHotel/'  ,  1);
insert into `Tborganizacion` values(16  ,  '11126'   ,   1  ,'Parque Nacional Natural Farallones de Cali, son formaciones rocosas que se encuentran en la Cordillera Occidental de los Andes. Si tu elección es la vertiente oriental, la recomendación es ir en enero y marzo y luego de julio a agosto.'   ,   'Una hermosa reserva donde se observa el paso del río en medio de un cañón con hermosas formaciones en mármol. En Río Claro se pueden hacer actividades como rafting, canopy, exploración de las cavernas y avistamiento de aves.'   ,  39  ,  ' Hotel numero-16'  ,  'direccion del hotel-16'  ,  '315-315-3325'  ,  '320-315-5255'  ,  'correohotelnumero176@correo.com'  ,  2  ,  93  ,  'dir16/imgHotel/'  ,  1);
insert into `Tborganizacion` values(17  ,  '11127'   ,   2  ,'Santuario de Fauna y Flora Otún Quimbaya, Ubicado en el flanco occidental de la Cordillera Central, en el departamento de Risaralda, el Santuario de Fauna y Flora Otún Quimbaya es un destino ecoturístico del Paisaje Cultural Cafetero.'   ,   'Una montaña que sobresale entre la selva, y con toda razón, ya que en ella se observan una serie de pinturas rupestres que conforman un hermoso mural de color rojizo y de gran valor histórico'   ,  39  ,  ' Hotel numero-17'  ,  'direccion del hotel-17'  ,  '315-315-3346'  ,  '320-315-5471'  ,  'correohotelnumero137@correo.com'  ,  6  ,  101  ,  'dir17/imgHotel/'  ,  1);
insert into `Tborganizacion` values(18  ,  '11128'   ,   2  ,'Parque Nacional Natural Tatamá,  podrás conocer tres importantes páramos colombianos, el Tatamá, el Frontino y el Duende, sin duda será una experiencia invaluable que te hará disfrutar de la biodiversidad colombiana.'   ,   'No hay carros ni motos, todo el pueblo se recorre a pie, y hay un mirador para disfrutar la espectacular vista que este pueblo tiene para ofrecer.'   ,  39  ,  ' Hotel numero-18'  ,  'direccion del hotel-18'  ,  '315-315-3367'  ,  '320-315-5687'  ,  'correohotelnumero133@correo.com'  ,  7  ,  115  ,  'dir18/imgHotel/'  ,  1);
insert into `Tborganizacion` values(19  ,  '11129'   ,   3  ,'Reserva Natural Cañón del Río Claro Ubicado en Antioquia, la biodiversidad de esta región es conocida como la cuenca media del Río Magdalena, además está situada en el piedemonte oriental de la Cordillera Central colombiana.'   ,   'La construcción es de estilo neogótico y está hecha en piedra gris y blanca. Ha sido catalogada como una de las iglesias más bonitas del mundo por el diario británico The Telegraph'   ,  39  ,  ' Hotel numero-19'  ,  'direccion del hotel-19'  ,  '315-315-3388'  ,  '320-315-5903'  ,  'correohotelnumero138@correo.com'  ,  4  ,  186  ,  'dir19/imgHotel/'  ,  1);
insert into `Tborganizacion` values(20  ,  '11130'   ,   1  ,'Parque Nacional Natural Las Orquídeas,  sus variados paisajes, además de una gran biodiversidad de ecosistemas, abundantes orquídeas y otras especies asociadas.'   ,   'Esta área protegida de 6 km cuadrados, alberga formaciones milenarias creadas a partir del viento y el agua y que ha dado lugar a columnas, pedestales cuevas y cavernas, que forman un paisaje único de formas quebradizas y erosionadas.'   ,  39  ,  ' Hotel numero-20'  ,  'direccion del hotel-20'  ,  '315-315-3409'  ,  '320-315-6119'  ,  'correohotelnumero194@correo.com'  ,  2  ,  82  ,  'dir20/imgHotel/'  ,  1);
insert into `Tborganizacion` values(21  ,  '11131'   ,   3  ,'Situada en la vía Tocaima – Viotá y está especialmente diseñada para descansar y descomunicarse del mundo exterior, gozando de una piscina cómoda, mangos y limones propios de la finca. La cabaña cuenta con las siguientes características:'   ,   'Parque Natural Chingaza se encuentra entre los 800 y 4.020 msnm. Extensión es de 53.385 hectáreas y tiene cuatro tipos de clima: cálido, templado, frío y páramo. La temperatura oscila entre los 4 y los 21.5 grados centígrados'   ,  39  ,  ' Hotel numero-21'  ,  'direccion del hotel-21'  ,  '315-315-3410'  ,  '320-315-6120'  ,  'correohotelnumero145@correo.com'  ,  5  ,  155  ,  'dir21/imgHotel/'  ,  1);
insert into `Tborganizacion` values(22  ,  '11132'   ,   1  ,'Habitacion con vista al mar amobladas'   ,   'El Cañón de Chicamocha estuvo nominado para ser incluído como una de las siete maravillas naturales del mundo. Es uno de los principales atractivos de Santander, pues sus paradisíacos paisajes lo convierten en un espectáculo visual único'   ,  39  ,  ' Hotel numero-22'  ,  'direccion del hotel-22'  ,  '315-315-3411'  ,  '320-315-6121'  ,  'correohotelnumero105@correo.com'  ,  1  ,  96  ,  'dir22/imgHotel/'  ,  1);
insert into `Tborganizacion` values(23  ,  '11133'   ,   3  ,'Hermosos paisajes de Antioquia'   ,   'Los bosques andinos, páramos y glaciar son sus ecosistemas predominantes.  cuenta con hermosos paisajes formados por las cuencas hidrográficas de algunos ríos, como: el Totarito, el Azufrado, el Otún, Gualí y el Campoalegre, entre otros.'   ,  39  ,  ' Hotel numero-23'  ,  'direccion del hotel-23'  ,  '315-315-3412'  ,  '320-315-6122'  ,  'correohotelnumero160@correo.com'  ,  1  ,  130  ,  'dir23/imgHotel/'  ,  1);
insert into `Tborganizacion` values(24  ,  '11134'   ,   2  ,'El Bleu Hills Glamping Llanogrande está situado en Rionegro, en la región de Antioquia, y ofrece alojamiento con aparcamiento privado gratuito y acceso a una bañera de hidromasaje.'   ,   'Este nevado tiene una altura de 5.220 posee la masa glaciar más pequeña de Colombia.  Sus paisajes llaman la atención de montañistas de todo el mundo, quienes asumen el reto de escalar la majestuosa montaña'   ,  39  ,  ' Hotel numero-24'  ,  'direccion del hotel-24'  ,  '315-315-3413'  ,  '320-315-6123'  ,  'correohotelnumero162@correo.com'  ,  5  ,  91  ,  'dir24/imgHotel/'  ,  1);
insert into `Tborganizacion` values(25  ,  '11135'   ,   3  ,'El Chalet Ecoturismo La Nohelia, situado en Jericó, rodeado por los cultivos de café famosos de la zona, ofrece restaurante y préstamo de bicicletas.'   ,   'Conocido también con el nombre de Paramillo del Cisne.  ubicado en la Cordillera Central, en el interior del Parque Nacional Natural Los Nevados. Tiene una altura de 4.636 msnm.'   ,  39  ,  ' Hotel numero-25'  ,  'direccion del hotel-25'  ,  '315-315-3414'  ,  '320-315-6124'  ,  'correohotelnumero142@correo.com'  ,  2  ,  232  ,  'dir25/imgHotel/'  ,  1);
insert into `Tborganizacion` values(26  ,  '11136'   ,   1  ,'El Santa Fé Hostel se encuentra a 3,8 km del parque acuático Kanaloa. El camping proporciona WiFi gratuita. El aeropuerto Olaya Herrera, el más cercano, está a 62 km del camping.'   ,   'Sus paisajes de caminos empedrados y grandes rocas blancas, ascienden hacia los vestigios de lo que fue el hábitat de los antepasados prehispánicos, asentados en las partes altas y en el litoral, desde los siglos VI y VII y hasta el siglo XVI.'   ,  39  ,  ' Hotel numero-26'  ,  'direccion del hotel-26'  ,  '315-315-3415'  ,  '320-315-6125'  ,  'correohotelnumero138@correo.com'  ,  5  ,  85  ,  'dir26/imgHotel/'  ,  1);
insert into `Tborganizacion` values(27  ,  '11137'   ,   3  ,'El Aguayacanes se encuentra en San Rafael y ofrece un jardín. Guatapé se encuentra a 15 km del camping, mientras que Barbosa está a 38 km.'   ,   'La principal ciudad turística del golfo es Tolú. A cinco kilómetros de su centro, se encuentran «Las Playas del Francés», cuyos paisajes se caracterizan por sus arenas blancas.'   ,  39  ,  ' Hotel numero-27'  ,  'direccion del hotel-27'  ,  '315-315-3416'  ,  '320-315-6126'  ,  'correohotelnumero101@correo.com'  ,  4  ,  160  ,  'dir27/imgHotel/'  ,  1);
insert into `Tborganizacion` values(28  ,  '11138'   ,   3  ,'Colombia cuenta con un sistema de Parques Nacionales Naturales que permite al visitante apreciar la majestuosidad de nuestra geografía, así como la riqueza de nuestra fauna y flora. Conoce algunas curiosidades de Colombia '   ,   'En esta península estan los hermosísimos paisajes del Cabo de la Vela, un imponente terreno desértico habitado, en su mayoría, por la cultura wayúu. Los indígenas le llaman Jepirra. Para ellos, se trata de un territorio sagrado.'   ,  39  ,  ' Hotel numero-28'  ,  'direccion del hotel-28'  ,  '315-315-3417'  ,  '320-315-6127'  ,  'correohotelnumero167@correo.com'  ,  3  ,  239  ,  'dir28/imgHotel/'  ,  1);
insert into `Tborganizacion` values(29  ,  '11139'   ,   2  ,' El primer Parque Nacional Natural de Colombia fue La Cueva de los Guácharos, declarado el 9 de noviembre de 1960. Por esa razón, en esta fecha se celebra el Día de los Parques Naturales en nuestro país. '   ,   'Impactantes paisajes que ofrece la montaña más alta de Colombia, compuestos por los valles que forman los ríos Ranchería y Cesar. Se encuentra el Parque Arqueológico Teyuna “Ciudad Perdida”, es una inimaginable de bellísimos paisajes.'   ,  39  ,  ' Hotel numero-29'  ,  'direccion del hotel-29'  ,  '315-315-3418'  ,  '320-315-6128'  ,  'correohotelnumero137@correo.com'  ,  1  ,  91  ,  'dir29/imgHotel/'  ,  1);
insert into `Tborganizacion` values(30  ,  '11140'   ,   2  ,'El Parque Nacional Natural Uramba Bahía Málaga.  se ubica en las costas del pacífico colombiano y es reconocido internacionalmente por ser un privilegiado escenario para apreciar la migración de ballenas jorobadas'   ,   'Contiene una gran variedad de ecosistemas que van desde el selvático hasta el marino, dando vida a paisajes majestuosos formados por manglares, arrecifes coralinos, estuarios y fondo marino y litoral de más de 10.000 hectáreas de Océano'   ,  39  ,  ' Hotel numero-30'  ,  'direccion del hotel-30'  ,  '315-315-3419'  ,  '320-315-6129'  ,  'correohotelnumero155@correo.com'  ,  2  ,  120  ,  'dir30/imgHotel/'  ,  1);
insert into `Tborganizacion` values(31  ,  '11141'   ,   2  ,'El Parque Las Orquídeas se presenta como uno de los lugares ideales para observar nuestra diversidad de flora y fauna.'   ,   'Por su importancia físico biótica, origina los más bellos paisajes imaginables. entre ellos puede apreciarse en Caño Cristales, además de enormes cascadas, como la de Caño Canoas, Soplaculos, el Salto del Mico, el Salto de Yarumales y muchas mas'   ,  39  ,  ' Hotel numero-31'  ,  'direccion del hotel-31'  ,  '315-315-3420'  ,  '320-315-6130'  ,  'correohotelnumero164@correo.com'  ,  3  ,  91  ,  'dir31/imgHotel/'  ,  1);
insert into `Tborganizacion` values(32  ,  '11142'   ,   3  ,'Las 15.000 hectáreas del Parque Natural Nacional Tayrona ofrecen al visitante una paradisíaca combinación de naturaleza, historia precolombina, aventura y relajación.'   ,   'Región de increíbles paisajes, delimitada por el Río Orinoco. la actividad económica es la ganadería, la agricultura y la extracción de petróleo. Allí, se encuentra Caño Limón, y diversos proyectos energéticos basados en la energía eólica.'   ,  39  ,  ' Hotel numero-32'  ,  'direccion del hotel-32'  ,  '315-315-3421'  ,  '320-315-6131'  ,  'correohotelnumero200@correo.com'  ,  1  ,  243  ,  'dir32/imgHotel/'  ,  1);
insert into `Tborganizacion` values(33  ,  '11143'   ,   2  ,'La Playa La Aguada, ubicada en el Parque Natural Utría, es la primera playa de Colombia con certificación en turismo sostenible.'   ,   'La Sierra o Serranía de Chiribiquete:  en conjunto de la Serranía de la Macarena y la Sierra de Naquén, son los sistemas montañosos más importantes de la región amazónica colombiana, ofrecen majestuosos paisajes llenos de historia.'   ,  39  ,  ' Hotel numero-33'  ,  'direccion del hotel-33'  ,  '315-315-3422'  ,  '320-315-6132'  ,  'correohotelnumero184@correo.com'  ,  4  ,  103  ,  'dir33/imgHotel/'  ,  1);
insert into `Tborganizacion` values(34  ,  '11144'   ,   3  ,'Colombia es uno de los países con más biodiversidad en el mundo, los colores, la fauna y la flora que lo caracterizan son motivo de orgullo.'   ,   'El Trapecio Amazónico hace parte de una reserva natural llamada Parque Nacional Natural Amacayacu, traduce «Ríos de las Hamacas» en la lengua Quechua. fue creado a mediados de los años 70 para preservar la vida salvaje del Amazonas'   ,  39  ,  ' Hotel numero-34'  ,  'direccion del hotel-34'  ,  '315-315-3423'  ,  '320-315-6133'  ,  'correohotelnumero101@correo.com'  ,  2  ,  232  ,  'dir34/imgHotel/'  ,  1);
insert into `Tborganizacion` values(35  ,  '11145'   ,   3  ,'Santuario de Fauna y Flora Otún Quimbaya, Ubicado en el flanco occidental de la Cordillera Central, en el departamento de Risaralda, el Santuario de Fauna y Flora Otún Quimbaya es un destino ecoturístico del Paisaje Cultural Cafetero.'   ,   'Su cuenca hidrográfica también es la de mayor superficie en el mundo y, allí, se sustenta la selva amazónica. Su zona forestal de 483.119 km², es compartida por Brasil, Venezuela, Perú, Bolivia, Ecuador, Guyana y Suriname'   ,  39  ,  ' Hotel numero-35'  ,  'direccion del hotel-35'  ,  '315-315-3424'  ,  '320-315-6134'  ,  'correohotelnumero199@correo.com'  ,  10  ,  176  ,  'dir35/imgHotel/'  ,  1);
insert into `Tborganizacion` values(36  ,  '11146'   ,   1  ,'Parque Nacional Natural Tatamá,  podrás conocer tres importantes páramos colombianos, el Tatamá, el Frontino y el Duende, sin duda será una experiencia invaluable que te hará disfrutar de la biodiversidad colombiana.'   ,   'La isla Malpelo tiene hermosos paisajes en sus acantiladas costas de formación volcánica. Está rodeada por once islotes de pequeños, conocidos como: «Los Mosqueteros», «Vagamares y La Torta» y «Los Tres Reyes».'   ,  39  ,  ' Hotel numero-36'  ,  'direccion del hotel-36'  ,  '315-315-3425'  ,  '320-315-6135'  ,  'correohotelnumero157@correo.com'  ,  1  ,  55  ,  'dir36/imgHotel/'  ,  1);
